-- Add detailed address fields to shop table
ALTER TABLE shop ADD COLUMN IF NOT EXISTS house_no VARCHAR(50);
ALTER TABLE shop ADD COLUMN IF NOT EXISTS street VARCHAR(255);
ALTER TABLE shop ADD COLUMN IF NOT EXISTS town VARCHAR(100);
ALTER TABLE shop ADD COLUMN IF NOT EXISTS state VARCHAR(100);
ALTER TABLE shop ADD COLUMN IF NOT EXISTS country VARCHAR(100);
